### ISSUE TITLE
Incorrect code segment in samples/solace-samples-c/publish-subscribe

### ISSUE THREAD

**Issue by ngdavid1013** [SolaceSamples/solace-samples-c#22]
In the page https://dev.solace.com/samples/solace-samples-c/publish-subscribe/,
the code segment in Session Creation has the following error:
The sessionProps[] array needs to end with a NULL entry.

So, the line:
sessionProps[propIndex] = password;

Needs to be changed to:
sessionProps[propIndex++] = password;

 sessionProps[propIndex] = NULL;

**Comment by aaron-613** [comment]
Tutorials now located here:  https://tutorials.solace.dev/c

Current fix, inside `common-assets/initC.md`:

```
initC.md:sessionProps[propIndex++] = SOLCLIENT_SESSION_PROP_PASSWORD;
initC.md:sessionProps[propIndex++] = password;
initC.md:sessionProps[propIndex++] = NULL;
initC.md:solClient_session_create ( ( char ** ) sessionProps,
```

@ngdavid1013 said the last "NULL" shouldn't have the `++`, but I don't think it makes a difference?  Any thoughts before closing?

**Comment by aaron-613** [comment]
Done, fixed.
