### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Arunkumar6274** [SolaceSamples/solace-samples-c#33]
solace-samples-c-master/lib/linux/x64/libsolclient.so: file format not recognized; treating as linker script

**Comment by Mrc0113** [comment]
Closing stale issue due to inactivity. 😴
To have this issue re-opened please add a comment below with a detailed explanation.
Thank you for your contributions ❤️

Note: when I just tried to build the samples based on instructions in the README (on mac) it worked successfully.
