### ISSUE TITLE
[Bug]: source ./setenv.sh does not work properly

### ISSUE THREAD

**Issue by ngdavid1013** [SolaceSamples/solace-samples-c#39]
### Bug Description

On linux, when you source ./setenv.sh, inside the script,
the $0 evaluates to /bin/bash
Everything falls apart from that point.
/usr/bin got added to LD_LIBRARY_PATH.

### Expected Behavior

The current bin directory is to be added to LD_LIBRARY_PATH.

### Steps to Reproduce

Just run it on linux.

### Solace Product

Other

**Comment by Mrc0113** [comment]
Thank you @ngdavid1013!

**Comment by gvensan** [comment]
Fixed in commit PR #40 (commit 3c746d4)
